classification_model: "variables/efficientnet_b3/best_model.pth.tar"
classification_model_custom: "variables/custom_skin_net/best_model.pth.tar"
yolo_model: "yolo_variables/checkpoint_yolo.pt"
batch_size: 16

test_data: "skin diseases/test"
eval_data: "skin diseases/val"
class_names: [
"痤疮和酒渣鼻","光化性角化病和基底细胞癌","特应性皮炎",
"大疱性疾病","蜂窝组织炎和细菌感染","湿疹",
"发疹和药物性皮炎","脱发","疱疹/HPV",
"色素性疾病","红斑狼疮","黑色素瘤和痣",
"甲真菌病","毒葛皮炎","银屑病和扁平苔藓",
"疥疮和莱姆病","脂溢性角化病和良性肿瘤","系统性疾病",
"真菌感染","荨麻疹","血管瘤",
"血管炎","疣和传染性软疣"
]








