# YOLOv10配置文件 - HAM10000 皮损检测
model_size: 'n'
path: HAM10000/yolo_dataset
train: images/train
val: images/val
nc: 1
names: ['lesion']
epochs: 50
batch_size: 16
lr0: 1e-3
imgsz: 640
data_yaml: 'HAM10000/yolo_dataset/data.yaml'
yolo_resume: 'false'
yolo_freeze: 10
use_lora: false
lora_r: 8
lora_alpha: 16
lora_dropout: 0.1
#pretrained_path: 'E:\py项目\Skin diseases\pretrained\hub\yolov10n.pt'